version: "3.9"

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - ./src/config/db/.docker.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - suppliers_dashboard_app

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - suppliers_dashboard_app

volumes:
  postgres_data:
    external: true
  redis_data:

networks:
  suppliers_dashboard_app:
    external: true
